name: 🚀 Feature Proposal (Form)
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
type: issue
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us improve!  
        Please describe your idea clearly and concisely.
  - type: input
    id: summary
    attributes:
      label: Summary
      placeholder: "Brief title for the proposed feature"
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: "What problem does this feature solve?"
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: "Describe how you’d like this to work"
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: "List any alternative approaches or workarounds"
